### ISSUE TITLE
CONFIG += c++11 not work on Linux

### ISSUE THREAD

**Issue by bo-wu** [OpenGP/starlab#1]
CONFIG += c++11 seems not work on Linux with QT5,
I have to use QMAKE_CXXFLAGS += -std=c++11  to compile starlab sucessfully

**Comment by ialhashim** [comment]
Thanks for reporting it, I looked it up and found this instance at SO http://stackoverflow.com/questions/27412373/qt-5-config-c11-vs-qmake-cxxflags-std-c11-whats-better

I have recently tried compiling on latest Ubuntu and Qt 5. Maybe the flag I used in the 'starlab.prf' global file should be changed to unix? https://github.com/OpenGP/starlab/blob/master/core/starlab.prf#L203

**Comment by bo-wu** [comment]
@ialhashim

**Comment by bo-wu** [comment]
@ialhashim I think you are right. I had thought the snippet (following) not work because of CONFIG.
 # GCC C++11
    linux-g++{
        CONFIG += c++11
    }

But now I move the CONFIG under some unix!mac, it works.  Maybe it is the problem of "linux-g++"

**Comment by taiya** [comment]
I've started the conversion to CMake. Once that's done all those problems will disappear
