### ISSUE TITLE
StarlabTemplate is not a recognized test function on WIndows

### ISSUE THREAD

**Issue by tanysheng** [OpenGP/starlab#4]
Hi guys, i downloaded Qt5 SDK mingw 32bits version for windows and along with Qt Creator. After that i test qmake, but no luck. "StarlabTemplate is not a recognized test function" errors showed up.

**Comment by ialhashim** [comment]
Hi, could you be specific about where this error happens, i.e., which plug in / project folder.

This seem to be either caused by some older code or not fully initialized compilation process (the starlabtemplate is defined early)

**Comment by tanysheng** [comment]
It is on render plugin. I using qt5.5 with mingw

**Comment by ialhashim** [comment]
It could be related to mingw... the file master/core/starlab.prf defines this function but we have not tried compiling starlab using this compiler so maybe some changes are still required.

I don't have much experience with this compiler, if you do manage to get things compiled would you please share the code changes. That would be wonderful, thanks.
