### ISSUE TITLE
 building the Starlab

### ISSUE THREAD

**Issue by zahrakheyrollahi** [OpenGP/starlab#7]
I want to implement the skeleton of 3D shapes and I have to [use](https://github.com/taiya/starlab-mcfskel) but I encounter the following errors
![qt2](https://github.com/OpenGP/starlab/assets/147084302/6af2bccb-0b63-44e6-ab99-cedc1c31c8cb)

**Comment by taiya** [comment]
See the CGAL implementation – starlab is no longer developed
